# =============================================================================
# roles/kubernetes/tasks/initialize_cluster.yml - Initialize Kubernetes Cluster
# =============================================================================
---
- name: "Create kubeadm configuration file on the first control plane node"
  template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml
    mode: '0640'
  when: inventory_hostname == groups['kube_control_plane'][0]
  tags: kubeadm_init



- name: "Initialize Kubernetes cluster with kubeadm"
  command: kubeadm init --config /tmp/kubeadm-config.yaml --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result
  when: inventory_hostname == groups['kube_control_plane'][0]
  tags: kubeadm_init

- name: "Extract and store certificate key from init output"
  shell: |
    echo "{{ kubeadm_init_result.stdout }}" | grep -A 1 "certificate key:" | tail -1 > /tmp/kubeadm_cert_key
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - kubeadm_init_result.changed
  tags: kubeadm_init
  
- name: "Create .kube directory for admin user"
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: inventory_hostname == groups['kube_control_plane'][0]
  
- name: "Display kubeadm init output for debugging"
  debug:
    var: kubeadm_init_result.stdout_lines
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - kubeadm_init_result.changed
  tags: kubeadm_init

- name: "Wait for kubelet.conf to be generated by kubeadm"
  wait_for:
    path: /etc/kubernetes/kubelet.conf
    timeout: 60
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - kubeadm_init_result.changed
  tags: kubeadm_init

- name: "Verify kubelet.conf was generated correctly"
  shell: |
    echo "=== kubelet.conf content ==="
    cat /etc/kubernetes/kubelet.conf
    echo ""
    echo "=== kubelet.conf permissions ==="
    ls -la /etc/kubernetes/kubelet.conf
  register: kubelet_conf_verification
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - kubeadm_init_result.changed
  tags: kubeadm_init

- name: "Display kubelet.conf verification results"
  debug:
    var: kubelet_conf_verification.stdout_lines
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - kubeadm_init_result.changed
    - kubelet_conf_verification.stdout_lines is defined
  tags: kubeadm_init
