# =============================================================================
# roles/kubernetes/tasks/main.yml - Main Kubernetes Tasks
# =============================================================================
---
- name: "Display Kubernetes phase information"
  debug:
    msg: |
      🚀 KubePilot Kubernetes Phase
      =============================
      Kubernetes Version: {{ kube_version }}
      Control Plane Endpoint: {{ hostvars[groups['kube_control_plane'][0]].ansible_host }}
  tags: always

- name: "Install Kubernetes components"
  import_tasks: install_kubernetes.yml
  tags:
    - kubernetes
    - install
    - binaries

- name: "Configure kubelet before initialization"
  import_tasks: configure_kubelet.yml
  tags:
    - kubernetes
    - configure
    - kubelet

- name: "Initialize Kubernetes cluster"
  import_tasks: initialize_cluster.yml
  when: inventory_hostname == groups['kube_control_plane'][0]
  tags:
    - kubernetes
    - initialize
    - controlplane

- name: "Configure kubeconfig for users"
  import_tasks: configure_kubeconfig.yml
  when: inventory_hostname == groups['kube_control_plane'][0]
  tags:
    - kubernetes
    - kubeconfig

- name: "Enable shell completions"
  import_tasks: enable_completion.yml
  when: inventory_hostname == groups['kube_control_plane'][0]
  tags:
    - kubernetes
    - completion

- name: "Join additional control plane nodes"
  import_tasks: join_control_plane.yml
  when: inventory_hostname in groups['kube_control_plane'] and inventory_hostname != groups['kube_control_plane'][0]
  tags:
    - kubernetes
    - join
    - controlplane
