# =============================================================================
# roles/node/tasks/main.yml - Worker Node Setup and Cluster Joining
# =============================================================================
---
- name: "Display worker node phase information"
  debug:
    msg: |
      🔧 KubePilot Worker Node Phase
      ==============================
      Node: {{ inventory_hostname }}
      Target Cluster: {{ hostvars[groups['kube_control_plane'][0]].ansible_host }}

- name: "Install Kubernetes node components"
  import_tasks: install_node_components.yml
  tags:
    - install
    - components

- name: "Join worker node to cluster"
  import_tasks: join_worker_node.yml
  tags:
    - join
    - cluster

- name: "Configure worker node post-join"
  import_tasks: configure_worker.yml
  tags:
    - configure
    - post-join

- name: "Apply node labels"
  import_tasks: apply_labels.yml
  tags:
    - labels
    - node-labels
