# roles/base/tasks/hostname.yml
---
- name: Backup /etc/hosts file
  copy:
    src: /etc/hosts
    dest: "/etc/hosts{{ backup_suffix }}"
    remote_src: true
    mode: '0644'
  when: backup_configs | default(true)
  become: true
  tags: ['hostname', 'backup']

- name: Ensure localhost entries in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
    insertbefore: BOF
  loop:
    - "127.0.0.1 localhost localhost.localdomain"
    - "::1 localhost localhost.localdomain"
  become: true
  tags: ['hostname', 'localhost']

- name: Ensure local hostname mapping in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address | default('127.0.0.1') }} {{ inventory_hostname }} {{ inventory_hostname }}.local"
    state: present
    regexp: "^{{ ansible_default_ipv4.address | default('127.0.0.1') }}\\s+{{ inventory_hostname }}"
  become: true
  tags: ['hostname', 'local']

- name: Configure hostname resolution for cluster nodes
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host | default(hostvars[item].ansible_default_ipv4.address) }} {{ item }} {{ hostvars[item].ansible_hostname | default(item) }}"
    state: present
    regexp: "^{{ hostvars[item].ansible_host | default(hostvars[item].ansible_default_ipv4.address) }}\\s+{{ item }}"
  loop: "{{ groups['all'] }}"
  when: 
    - configure_hostname_resolution | default(true)
    - hostvars[item].ansible_host is defined or hostvars[item].ansible_default_ipv4 is defined
  become: true
  notify: validate hostname resolution
  tags: ['hostname', 'cluster']

- name: Set system hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when: ansible_hostname != inventory_hostname
  tags: ['hostname', 'system']

- name: Ensure hostname persists after reboot
  lineinfile:
    path: "{{ hostname_file }}"
    line: "{{ inventory_hostname }}"
    create: true
    mode: '0644'
  become: true
  when: hostname_file is defined
  tags: ['hostname', 'persistent']

- name: Verify hostname resolution configuration
  shell: |
    echo "=== /etc/hosts content ==="
    cat /etc/hosts
    echo ""
    echo "=== Hostname resolution test ==="
    nslookup {{ inventory_hostname }} 127.0.0.1 || echo "nslookup failed, checking /etc/hosts directly"
    grep -E "^{{ ansible_default_ipv4.address | default('127.0.0.1') }}\\s+{{ inventory_hostname }}" /etc/hosts || echo "Local hostname mapping not found"
  register: hostname_verification
  become: true
  tags: ['hostname', 'verify']

- name: Display hostname verification results
  debug:
    var: hostname_verification.stdout_lines
  when: hostname_verification.stdout_lines is defined
  tags: ['hostname', 'verify']
