# roles/base/tasks/swap.yml
---
- name: Check current swap status
  command: swapon --show
  register: swap_status
  changed_when: false
  failed_when: false
  become: true
  tags: ['swap', 'check']

- name: Disable swap immediately
  command: swapoff -a
  when: 
    - disable_swap | default(true)
    - swap_status.stdout | length > 0
  become: true
  tags: ['swap', 'disable']

- name: Remove swap entries from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '# \1'
    backup: "{{ backup_configs | default(true) }}"
  when: disable_swap | default(true)
  become: true
  tags: ['swap', 'fstab']

- name: Verify swap is disabled
  command: swapon --show
  register: swap_verify
  changed_when: false
  failed_when: swap_verify.stdout | length > 0
  when: disable_swap | default(true)
  become: true
  tags: ['swap', 'verify']
